### ISSUE TITLE
Update to Postgis 2.2

### ISSUE THREAD

**Issue by obrhoff** [kidpixo/postgis-2.0.2#1]
It would be great to have this documentation in it's latest and greatest iteration :-)

**Comment by kidpixo** [comment]
I would love to, but I didn't switch yet, so I don't have hurry to have it.
If enough requests will come, I cant think about it.

**Comment by timiyay** [comment]
G'day @kidpixo, thanks for this docset, I'm really hooked on Dash so I like having PostGIS docs at my fingertips.

I was thinking about building an updated PostGIS docset, but thought maybe it's better if I contribute to your repo instead. Are you able to share the process you used for generating your docset? Did you build them with Doxygen, or use the HTML docs?

**Comment by kidpixo** [comment]
Hi timiyay, I used a variant of my python code [IDLdoc](https://github.com/kidpixo/IDLdoc). 
Essentialy you should have the whole html documentation at hand (or create it with Doxygen, but I never really try) and parse it with python, extracting information from each html page and putting them in an index file called docSet.dsidx. 
More info on kapeli's page on [Dash Docsets](http://kapeli.com/docsets#dashDocset). If you need more info, feel free to write!! I'll see if I find the original code I used to create this repo.

**Comment by drewda** [comment]
I just created a docset for PostGIS 2.1.5 (that's the current version, right?): https://github.com/drewda/postgis-docset
